### ISSUE TITLE
Improve design of front page

### ISSUE THREAD

**Issue by dracos** [mysociety/2015wards#1]

**Comment by TomSteinberg** [comment]
For designers. Here is the page description diagram:

**High priority**

Search box
Message - Find out what ward you're in for the election!

**Medium**

Message - Look - commercial clients! we have all this up to date data via API!
Message - 'Has my ward changed? I've heard it might have.'
mySociety branding
mapit branding - 'powered by mapit'

**Low priority**

Why are boundaries changing? What even is a ward?
All the dull data credits
The django pony - steve suggests it has been deprocated
donate - not really necessary here

**Comment by zarino** [comment]
<p><del>@dracos @TomSteinberg – 2015 Wards is currently styled as part of the MapIt family of products. Is this something you want to keep? And if so, why?</del></p>

The answer was yes, it was intended, and given the short timescale it's probably simplest to keep it for now.

**Comment by zarino** [comment]
Quick mockup in google docs:

![mapit- which ward am i in-](https://cloud.githubusercontent.com/assets/739624/6944030/a148b36a-d889-11e4-924f-6f344e9f875d.png)

Keeping a lot of the MapIt styling, for expediency. Although demoting "MapIt" in the header, since this is a project that uses MapIt, not part of MapIt itself.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/2015wards/issues/7

![wwaai](https://cloud.githubusercontent.com/assets/739624/6946743/5cb55cf6-d89a-11e4-84e6-c0030bae2770.png)
